In [1]:
from sklearn.svm import SVC
from sklearn.datasets import make_classification
from sklearn.multiclass import OneVsOneClassifier

from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import classification_report, confusion_matrix

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

### Public variables

In [2]:
num_class = 3
classes = ("functional", "functional needs repair","non-functional")

In [3]:
train_df = pd.read_csv("./datasets/merged_train.csv")
test_df = pd.read_csv("./datasets/test.csv")
submission_df = pd.read_csv("./datasets/SubmissionFormat.csv")

In [4]:
input_df = train_df.drop("status_group", axis=1)
output_df = train_df["status_group"]

In [5]:
print(input_df.shape)
print(output_df.shape)

(59400, 28)
(59400,)


In [6]:
### Split Dataset

In [7]:
input_train, input_test, output_train, output_test = tts(input_df, output_df, test_size=0.3)

In [8]:
svc_classifier = SVC(decision_function_shape='ovo')
svc_classifier.fit(input_train, output_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [9]:
output_prediction = svc_classifier.predict(input_test)

In [10]:
print(confusion_matrix(output_test, output_prediction))

[[9610    0    0]
 [1294    0    0]
 [6916    0    0]]


In [11]:
print(classification_report(output_test, output_prediction))

precision    recall  f1-score   support

           0       0.54      1.00      0.70      9610
           1       0.00      0.00      0.00      1294
           2       0.00      0.00      0.00      6916

    accuracy                           0.54     17820
   macro avg       0.18      0.33      0.23     17820
weighted avg       0.29      0.54      0.38     17820



In [12]:
svm_model = SVC()
ovo_classifier = OneVsOneClassifier(svm_model)
ovo_classifier.fit(input_train, output_train)

OneVsOneClassifier(estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                                 class_weight=None, coef0=0.0,
                                 decision_function_shape='ovr', degree=3,
                                 gamma='scale', kernel='rbf', max_iter=-1,
                                 probability=False, random_state=None,
                                 shrinking=True, tol=0.001, verbose=False),
                   n_jobs=None)

In [13]:
output_prediction_one = ovo_classifier.predict(input_test)

In [14]:
print(confusion_matrix(output_test, output_prediction_one))

[[9610    0    0]
 [1294    0    0]
 [6916    0    0]]


In [15]:
print(classification_report(output_test, output_prediction_one))

precision    recall  f1-score   support

           0       0.54      1.00      0.70      9610
           1       0.00      0.00      0.00      1294
           2       0.00      0.00      0.00      6916

    accuracy                           0.54     17820
   macro avg       0.18      0.33      0.23     17820
weighted avg       0.29      0.54      0.38     17820

